apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-triggers
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tektoncd/triggers.git  # GitHub-Repository für Tekton Triggers
    targetRevision: v0.27.0  # Feste Version für Stabilität
    path: .  # Der Pfad zur release.yaml (liegt im Root des Tags)
    directory:
      include: release.yaml  # Nur die release.yaml anwenden
  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-pipelines
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true