apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-triggers
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/MarkusJackson/azure-infra-gitops.git
      targetRevision: main
      path: 4-helm-charts-and-manifests/tekton-triggers-manifest
      directory:
        include: release.yaml
    - repoURL: https://github.com/MarkusJackson/azure-infra-gitops.git
      targetRevision: main
      path: 4-helm-charts-and-manifests/tekton-triggers-manifest
      directory:
        include: interceptors.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-pipelines
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true