apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-triggers
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/tektoncd/triggers.git
      targetRevision: v0.27.0
      path: .
      directory:
        include: release.yaml
    - repoURL: https://github.com/tektoncd/triggers.git
      targetRevision: v0.27.0
      path: .
      directory:
        include: interceptors.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-pipelines
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true