apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 03-infra-tekton-pipelines-definitions
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/markusjackson/azure-infra-gitops.git
    targetRevision: main
    path: 4-helm-charts-and-manifests/tekton-pipelines-definitions-manifests
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-pipelines
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true