apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-build-eventlistener-role
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/part-of: tekton-pipelines
rules:
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["eventlisteners", "triggerbindings", "triggertemplates", "triggers", "interceptors"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-build-eventlistener-binding
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/part-of: tekton-pipelines
subjects:
  - kind: ServiceAccount
    name: tekton-build
    namespace: tekton-pipelines
roleRef:
  kind: Role
  name: tekton-build-eventlistener-role
  apiGroup: rbac.authorization.k8s.io