# Diese Datei definiert eine SecretProviderClass, die es Kubernetes erlaubt, Secrets aus Azure Key Vault abzurufen.
# Sie verbindet den Secrets Store CSI Driver mit dem Key Vault playgr-cluster-key-vault und erstellt ein Kubernetes Secret namens docker-credentials,
# das die Tekton-Pipeline verwendet, um sich bei Docker Hub zu authentifizieren.
# Der Secret docker-pat (der Docker PAT) wird zur Laufzeit aus dem Key Vault abgerufen, um Sicherheitsrisiken durch das Speichern in Git zu vermeiden.
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-playground-cluster-vault
  namespace: tekton-pipelines
spec:
  provider: azure
  secretObjects:
    - secretName: docker-credentials
      type: kubernetes.io/dockerconfigjson
      data:
        - objectName: docker-pat
          key: .dockerconfigjson
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: "1bbfa138-4f01-46b9-85cd-e683395b2eca"
    keyvaultName: "playgr-cluster-key-vault"
    objects: |
      array:
        - |
          objectName: docker-pat
          objectType: secret
          objectAlias: .dockerconfigjson
    tenantId: "8359ecb7-bd5c-4515-b5c8-aef88eb0a333"