apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-build-clusterrole
  labels:
    app.kubernetes.io/part-of: tekton-pipelines
rules:
  - apiGroups: ["tekton.dev"]
    resources: ["pipelines", "tasks", "pipelineruns", "taskruns"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-build-clusterbinding
  labels:
    app.kubernetes.io/part-of: tekton-pipelines
subjects:
  - kind: ServiceAccount
    name: tekton-build
    namespace: tekton-pipelines
roleRef:
  kind: ClusterRole
  name: tekton-build-clusterrole
  apiGroup: rbac.authorization.k8s.io