apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-build-clusterrole
  labels:
    app.kubernetes.io/part-of: tekton-pipelines
rules:
  # Berechtigungen für Tekton-Ressourcen (bereits vorhanden)
  - apiGroups: ["tekton.dev"]
    resources: ["pipelines", "tasks", "pipelineruns", "taskruns"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  # Neue Berechtigungen für Tekton-Triggers-Ressourcen
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["eventlisteners", "triggers", "triggerbindings", "triggertemplates", "clustertriggerbindings", "clusterinterceptors", "interceptors"]
    verbs: ["get", "list", "watch"]
  # Neue Berechtigungen für die SecretProviderClass
  - apiGroups: ["secrets-store.csi.x-k8s.io"]
    resources: ["secretproviderclasses"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-build-clusterbinding
  labels:
    app.kubernetes.io/part-of: tekton-pipelines
subjects:
  - kind: ServiceAccount
    name: tekton-build
    namespace: tekton-pipelines
roleRef:
  kind: ClusterRole
  name: tekton-build-clusterrole
  apiGroup: rbac.authorization.k8s.io