apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-build-role-binding
  namespace: kafka-playground  # Angepasst von hello-world-2
subjects:
  - kind: ServiceAccount
    name: tekton-build
    namespace: tekton-pipelines
roleRef:
  kind: Role
  name: tekton-build-role
  apiGroup: rbac.authorization.k8s.io