apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-of-apps-infra
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - appName: tekton-pipelines
            path: 3-argocd-apps/argocd-tekton-pipelines-application.yaml
          - appName: tekton-triggers
            path: 3-argocd-apps/argocd-tekton-triggers-application.yaml
            dependsOn:
              - tekton-pipelines
          - appName: tekton-resources
            path: 3-argocd-apps/argocd-tekton-resources-application.yaml
            dependsOn:
              - tekton-triggers
  template:
    metadata:
      name: "{{appName}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/MarkusJackson/azure-infra-gitops.git
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true