apiVersion: v1
kind: Secret
metadata:
  name: docker-credentials
  namespace: tekton-pipelines
  annotations:
    tekton.dev/docker-0: https://docker.io
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://docker.io": {
          "username": "markusjackson",
          "password": "dckr_pat_yourtoken123",
          "auth": "$(echo -n 'markusjackson:dckr_pat_yourtoken123' | base64)"
        }
      }
    }