apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push
  namespace: tekton-pipelines
spec:
  params:
    - name: git-url
      description: The URL of the Git repository
    - name: image-url
      description: The image name to build and push
  steps:
    - name: clone-build-push
      image: gcr.io/kaniko-project/executor:latest
      script: |
        #!/usr/bin/env sh
        git clone $(params.git-url) /workspace/source
        cd /workspace/source
        kaniko --context=/workspace/source --destination=$(params.image-url) --skip-tls-verify