apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push
  namespace: tekton-pipelines
spec:
  params:
    - name: git-url
      description: The URL of the Git repository
    - name: image-url
      description: The image name to build and push
  steps:
    - name: clone-build-push
      image: gcr.io/kaniko-project/executor:latest
      env:
        - name: GIT_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: git-credentials
              key: password
      script: |
        #!/usr/bin/env sh
        git clone https://$(GIT_CREDENTIALS)@github.com/MarkusJackson/hello-world-microservice.git /workspace/source
        cd /workspace/source
        kaniko --context=/workspace/source --destination=$(params.image-url) --skip-tls-verify