apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-deployment
  namespace: tekton-pipelines
spec:
  params:
    - name: deployment-name  # Name des Deployments (z. B. hello-world)
      type: string
    - name: namespace  # Ziel-Namespace (z. B. hello-world)
      type: string
    - name: image-url  # URL des Images (z. B. docker.io/markusjackson/hello-world-microservice)
      type: string
    - name: image-tag  # Neuer Tag des Images (z. B. v2.0.0)
      type: string
  steps:
    - name: update-deployment-image
      image: bitnami/kubectl:latest
      script: |
        kubectl set image deployment/$(params.deployment-name) $(params.deployment-name)=$(params.image-url):$(params.image-tag) -n $(params.namespace) --record