apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-deployment
  namespace: tekton-pipelines
spec:
  params:
    - name: deployment
      description: The name of the deployment to update
    - name: image
      description: The new image to set for the deployment
    - name: namespace
      description: The namespace of the deployment
  steps:
    - name: update-deployment
      image: bitnami/kubectl:latest
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
      command:
        - kubectl
      args:
        - set
        - image
        - deployment/$(params.deployment)
        - "$(params.deployment)=$(params.image)"
        - -n
        - "$(params.namespace)"