apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-build-role
  namespace: tekton-pipelines
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns", "pipelines", "tasks"]
    verbs: ["get", "list", "create", "delete"]