apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-build-pipelines-role
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/part-of: tekton-pipelines
rules:
  - apiGroups: ["tekton.dev"]
    resources: ["pipelines", "tasks", "pipelineruns", "taskruns"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-build-pipelines-binding
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/part-of: tekton-pipelines
subjects:
  - kind: ServiceAccount
    name: tekton-build
    namespace: tekton-pipelines
roleRef:
  kind: Role
  name: tekton-build-pipelines-role
  apiGroup: rbac.authorization.k8s.io