apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-listener
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-build
  triggers:
    - name: github-push
      bindings:
        - ref: github-push-binding
      template:
        ref: pipeline-trigger-template
      params:
        - name: pipelineName
          value: hello-world-microservice-pipeline
        - name: pipelineNamespace
          value: tekton-pipelines