apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-push-binding
  namespace: tekton-pipelines
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: gitrepositoryurl
      value: $(body.repository.url)
    - name: image-url
      value: "$(body.repository.full_name):$(body.head_commit.id)"  # Beispiel: Anpassbar
    - name: image-tag
      value: "$(body.head_commit.id)"  # Beispiel: Anpassbar
    - name: deployment-name
      value: "hello-world-deployment"  # Beispiel: Muss angepasst werden