apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-world-microservice-pipeline
  namespace: tekton-pipelines
spec:
  params:
    - name: gitrevision
    - name: gitrepositoryurl
    - name: image-url
    - name: image-tag
    - name: deployment-name
    - name: namespace
  tasks:
    - name: build-and-push
      taskRef:
        name: build-and-push
      params:
        - name: image
          value: "$(params.image-url):$(params.image-tag)"
        - name: context
          value: "$(params.gitrepositoryurl)"
    - name: update-deployment
      taskRef:
        name: update-deployment
      runAfter:
        - build-and-push
      params:
        - name: deployment
          value: "$(params.deployment-name)"
        - name: image
          value: "$(params.image-url):$(params.image-tag)"
        - name: namespace
          value: "$(params.namespace)"